//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.inventarios = new HashSet<inventario>();
        }
    
        public int idcliente { get; set; }
        public int idusuario { get; set; }
        public string nombrecliente { get; set; }
    
        public virtual ICollection<inventario> inventarios { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
