//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class entradaTarima
    {
        public int idtarimaentrada { get; set; }
        public int idreciboentrada { get; set; }
        public double peso { get; set; }
    
        public virtual reciboEntrada reciboEntrada { get; set; }
    }
}
