//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class inventarioEntities : DbContext
    {
        public inventarioEntities()
            : base("name=inventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cliente> cliente { get; set; }
        public DbSet<entradaTarima> entradaTarima { get; set; }
        public DbSet<inventario> inventario { get; set; }
        public DbSet<ordenOrigen> ordenOrigen { get; set; }
        public DbSet<ordenResultado> ordenResultado { get; set; }
        public DbSet<ordenTrabajo> ordenTrabajo { get; set; }
        public DbSet<proceso> proceso { get; set; }
        public DbSet<reciboEntrada> reciboEntrada { get; set; }
        public DbSet<reciboEntradaSacos> reciboEntradaSacos { get; set; }
        public DbSet<reciboSalida> reciboSalida { get; set; }
        public DbSet<reciboSalidaOrigen> reciboSalidaOrigen { get; set; }
        public DbSet<reciboSalidaSacos> reciboSalidaSacos { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<salidaTarima> salidaTarima { get; set; }
        public DbSet<usuario> usuario { get; set; }

        public virtual ObjectResult<Nullable<int>> getLastReciboEntradaID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getLastReciboEntradaID");
        }
    
        public virtual ObjectResult<Nullable<int>> getLastReciboSalidaID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getLastReciboSalidaID");
        }
    }
}
