//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenOrigen
    {
        public int idordenorigen { get; set; }
        public string tipoelemento { get; set; }
        public int idordentrabajo { get; set; }
        public string calidad { get; set; }
        public Nullable<int> cantidadsacos { get; set; }
        public Nullable<double> pesoneto { get; set; }
    
        public virtual ordenTrabajo ordenTrabajo { get; set; }
    }
}
