//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.clientes = new HashSet<cliente>();
        }
    
        public int idusuario { get; set; }
        public int idrol { get; set; }
        public string nombreusuario { get; set; }
        public string contrasena { get; set; }
    
        public virtual ICollection<cliente> clientes { get; set; }
        public virtual rol rol { get; set; }
    }
}
